### ISSUE TITLE
Initialisation of smStore

### ISSUE THREAD

**Issue by bcye** [paulw11/Seam3#100]
I need to intialise the SMStore variable in my Core Data Stack.
At the beginning of the README it says that I need to declare a variable:
`var smStore: SMStore`
Later it says that I can initialise it like the following:
`self.smStore = container.persistentStoreCoordinator.persistentStores.first as? SMStore`
But this returns an optional instance.

Do I need to make smStore an optional, or should I use an optional or throwing initializer?

**Comment by paulw11** [comment]
That looks like an error in the readme.

If you check the example app, `smStore` is declared as an optional.

I will update the documentation.
