### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by bcye** [paulw11/Seam3#102]
I want to start contributing to this project.

Is there a roadmap or a specific point where help is needed? I didn't find a CONTRIBUTING.md, but maybe that's because I'm bad at observation.

**Comment by paulw11** [comment]
There isn't a formal roadmap.  I don't actively use this library in any of my projects currently.  Typically people who are using it make requests or just submit pull requests

**Comment by bcye** [comment]
oh ok.
