### ISSUE TITLE
macOS, tvOS and watchOS targets do not compile.

### ISSUE THREAD

**Issue by lvandal** [paulw11/Seam3#104]
In version `1.4.9`, trying to compile those targets generate this error:

`/Seam3/Sources/Classes/SMStore.swift:232:36: Use of undeclared type 'SMLogDelegate'`

`SMLogger.swift` isn't included in those targets. Adding it fixes the issue.

**Comment by lvandal** [comment]
Version 1.5.1 still shows the issue. I believe you forgot to push the `.xcodeproj` file.

**Comment by paulw11** [comment]
I just ran a `pod try Seam3` and the macos and tvOS examples compiled correctly.

**Comment by lvandal** [comment]
Every source files are included in all 4 targets in the project, except for `SMLogger.swift`. I don't use Pods so adding the missing file to the targets (unless there's a reason for leaving it out?) would fix the issue.

<img width="1512" alt="screen shot 2019-01-08 at 4 46 47 pm" src="https://user-images.githubusercontent.com/157723/50860927-3f87cd80-1365-11e9-853b-b4d23b5c7c46.png">

**Comment by paulw11** [comment]
Ok.  I only ever use Pods, so I don't see the issue.

**Comment by paulw11** [comment]
When I check the file in the "pod try" workspace the logger file is a member of all targets
<img width="278" alt="image" src="https://user-images.githubusercontent.com/6835876/50861564-2d517200-13ed-11e9-948d-32490ba041c4.png">

What process do you use to integrate Seam3?

**Comment by paulw11** [comment]
Make sure you are opening the workspace and not the project

**Comment by lvandal** [comment]
The project file I'm referring to is `Seam3.xcodeproj

Carthage uses that project file to compile the targets.

<img width="654" alt="screen shot 2019-01-08 at 5 03 32 pm" src="https://user-images.githubusercontent.com/157723/50861637-56c7ba80-1367-11e9-8343-64d143dc02c5.png">

**Comment by paulw11** [comment]
Right.  I don't use Carthage for exactly these sorts of reasons.  I will push a new version
