### ISSUE TITLE
Items sync only on app restart

### ISSUE THREAD

**Issue by daviddelmonte** [paulw11/Seam3#11]
Using the Seam3 sample, I'm finding that items sync only when the app is restarted. Without being a bull in a china shop, and stomping all over the sample, do you have a suggestion where I could intervene to perform a forced sync, when a record change occurs?

Many thanks again.. Seam3 is great!

**Comment by paulw11** [comment]
Are you running on the simulator?  Push notifications are not supported on the simulator, so automatic sync will not occur. Running on a real device and changing a record on another device (including a simulator) or the CloudKit dashboard will trigger a sync

**Comment by daviddelmonte** [comment]
hmm. I’m running one version on the sim, and another on a device (iPad). I can’t get them to sync other than by restarting. I’m logging the transmissions, but do not see a received notification message. I have written a simple refresh (by button) that does work, but a more solid method would be terrific. I’m also trying to write an macOS version. Do you know if there is a backgroundFetch method for macOS?

David

**Comment by paulw11** [comment]
The example does work.  You need to make sure you are successfully registering for remote notifications.  Does your provisioning profile have remote notifications enabled? (capabilities tab). 
The process for registering for and handling the subscription notification on both iOS and OSX is described here: https://developer.apple.com/library/content/documentation/DataManagement/Conceptual/CloudKitQuickStart/SubscribingtoRecordChanges/SubscribingtoRecordChanges.html#//apple_ref/doc/uid/TP40014987-CH8-SW1

**Comment by daviddelmonte** [comment]
Found it. Sorry for the bother!
