### ISSUE TITLE
UISharingController

### ISSUE THREAD

**Issue by chadarutherford** [paulw11/Seam3#114]
When trying to create a CKRecord to send to the UISharing controller, I don't know how to instantiate a new CKRecord from my existing Datastore. If there's anyone who could assist me with this I'd be greatly appreciative

**Comment by paulw11** [comment]
You can't really use CloudKit sharing with Seam3 - Seam3 uses CloudKit to synchronise Core Data with the CloudKit being hidden as much as possible.  There is no easy way to access a specific CKRecord that corresponds to a Core Data object. 

If you want to use CloudKit sharing then you will need to implement CloudKit directly.
