### ISSUE TITLE
macOS and iOS

### ISSUE THREAD

**Issue by daviddelmonte** [paulw11/Seam3#12]
Paul, in the readMe, I see this section: "On iOS9 and macOS specify an options dictionary to the persistent store coordinator

```
let options:[String:Any] = [SMStore.SMStoreContainerOption:"iCloud.org.cocoapods.demo.Seam3-Example"]"
```
1. Can I specify any value here? 
2. While the readMe indicates specifying "On iOS9 and macOS ...", I only see the options listed for macOS.

My two versions are linked to the same custom CloudKit container in the "Capabilities" tag. I cannot figure what I'm missing in the two versions (iOS and macOS) don't sync..

Syncing is working fine amongst different iOS devices.

Thanks

**Comment by paulw11** [comment]
1. Yes, the value you specify here must match the container you have specified in the capabilities tag. 
2. What do you mean you only see the options listed for MacOS? The iOS10 version of the code is shown immediately above the "on ios9 and macOS..." section.  On iOS9, use the same code as you use on macOS.

**Comment by daviddelmonte** [comment]
Got it. Thanks
