### ISSUE TITLE
Not syncing in Testflight

### ISSUE THREAD

**Issue by brianminor** [paulw11/Seam3#120]
Not sure if this is a Seam3 issue. But I followed the setup guide and everything is working fine if I build directly to my devices. But when I upload to testflight and install from there nothing is getting synced.  Any thoughts?

**Comment by paulw11** [comment]
Did you use the CloudKit web console to move your CloudKit configuration to production?

**Comment by brianminor** [comment]
Nope 🤦🏻‍♂️ Very new to CloudKit Thanks!
