### ISSUE TITLE
No sync on early 13.4 simulators

### ISSUE THREAD

**Issue by daviddelmonte** [paulw11/Seam3#129]
Heads up. The two images show the same app running - one with a 13.3 simulator, and the next with a 13.4 simulator. I'm not experiencing this on macOS. I'll file a report with Apple unless there is a Seam3 issue.

13.3 sim:

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-13 at 11 59 06](https://user-images.githubusercontent.com/114487/79136337-d91b0780-7d7e-11ea-80a0-cf17eb5eaee2.png)

13.4 sim:

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-13 at 11 59 10](https://user-images.githubusercontent.com/114487/79136338-d9b39e00-7d7e-11ea-8429-f31c7a696d5d.png)

**Comment by ollisg1** [comment]
Had the same Problem on real devices as they were unable to create a uuid for the remote notifications. Still have no solution but seems to be an ios bug. Therefore on some devices which were not registered through a sim card the uuid was not generated (for example if the device was set up through wifi). The only solution for my test devices was to reset them and activate them with a sim card from my real device. I think the problem would be the same in simulator

**Comment by daviddelmonte** [comment]
Seems to be ok now (13.5+)
