### ISSUE TITLE
Both iOS and macOS Example is Buggy

### ISSUE THREAD

**Issue by kasimok** [paulw11/Seam3#131]
Hi I ran the example project without any modification to the code, XCode Version is 12.4 (12D4e)

On 2 platforms, the CoreData Complains about the model is not unique. 

  

> 2021-01-28 13:47:19.046207+0800 Seam3_Example[37794:3906867] [error] warning: Multiple NSEntityDescriptions claim the NSManagedObject subclass 'Event' so +entity is unable to disambiguate.
>   
>   CoreData: warning: Multiple NSEntityDescriptions claim the NSManagedObject subclass 'Event' so +entity is unable to disambiguate.
>   
>   2021-01-28 13:47:19.046351+0800 Seam3_Example[37794:3906867] [error] warning:  	 'Event' (0x6000008bd810) from NSManagedObjectModel (0x600001c8d540) claims 'Event'.
>   
>   CoreData: warning:  	 'Event' (0x6000008bd810) from NSManagedObjectModel (0x600001c8d540) claims 'Event'.
>   
>   2021-01-28 13:47:19.046424+0800 Seam3_Example[37794:3906867] [error] warning:  	 'Event' (0x6000008b82c0) from NSManagedObjectModel (0x600001ca8b90) claims 'Event'.
>   
>   CoreData: warning:  	 'Event' (0x6000008b82c0) from NSManagedObjectModel (0x600001ca8b90) claims 'Event'.
>   
>   2021-01-28 13:47:19.046482+0800 Seam3_Example[37794:3906867] [error] error: +[Event entity] Failed to find a unique match for an NSEntityDescription to a managed object subclass
>   
>   CoreData: error: +[Event entity] Failed to find a unique match for an NSEntityDescription to a managed object subclass

BTW i did not change the cloudkit settings but I guess that is not the cause of above errors, right?

**Comment by paulw11** [comment]
I can't reproduce this fault.  You should

- enter the `Example` directory
- run `pod install`
- open the created `Seam3.xcworkspace`

**Comment by tifroz** [comment]
I am seeing this warning as well in the Xcode logs, the user needs to create new data in order to see that entry in the logs

The Example app seems to function regardless (but it's unclear if something else might break?). The `backing store` and the `local store` have duplicate entities / model, but they each have their own `coordinators` and `contexts` so no obvious candidates for the source of the ambiguity off the top of my head
