### ISSUE TITLE
Changing model versions in macOS

### ISSUE THREAD

**Issue by daviddelmonte** [paulw11/Seam3#14]
I am able to change my core data graph on the iOS side of my app, by updating the model version. However, when I do this on macOS, I get SMStoreError 2, with the old "The managed object model version used to open the persistent store is incompatible..."

I'll keep digging but any pointers are welcome.

**Comment by paulw11** [comment]
Are you passing `true` for `NSMigratePersistentStoresAutomaticallyOption` when you create the store on Mac OS?

**Comment by daviddelmonte** [comment]
Hi Paul, thanks for replying. I had to change:

` let options:[String:Any] = [SMStore.SMStoreContainerOption:"iCloud.com.bohtech.xxx"]
`
to:

```
    let url = self.applicationDocumentsDirectory.appendingPathComponent("CodeCatching.storedata")
            do {
                let options:[String:Any] = [SMStore.SMStoreContainerOption:"iCloud.com.bohtech.xxx", NSInferMappingModelAutomaticallyOption : true,
                    NSMigratePersistentStoresAutomaticallyOption : true]
                
                self.smStore = try coordinator!.addPersistentStore(ofType: SMStore.type, configurationName: nil, at: url, options: options) as? SMStore
```
