### ISSUE TITLE
Accessing the user cloud kit on Apple Watch

### ISSUE THREAD

**Issue by daviddelmonte** [paulw11/Seam3#15]
Do you think it's possible for the watch to be able to access the specially named user cloud kit container? I'd like to port my app to that device.

Thanks

**Comment by paulw11** [comment]
I will have to look at it.  WatchOS doesn't support subscriptions, so there won't be support for pushed updates.

**Comment by daviddelmonte** [comment]
Thanks!

**Comment by daviddelmonte** [comment]
Thinking, maybe I can push the local CD info. It won't be interactive, but it might be enough..

**Comment by hyerra** [comment]
Yeah this would be a great addition! I believe [CloudCore](https://github.com/Sorix/CloudCore) handles this by making sure the platform isn't watchOS and then creating subscriptions.

**Comment by daviddelmonte** [comment]
I'll give this a try asap... Thanks for your efforts.

**Comment by paulw11** [comment]
Added (thanks to @hyerra) in 1.4.7
