### ISSUE TITLE
Trouble with image data

### ISSUE THREAD

**Issue by daviddelmonte** [paulw11/Seam3#16]
I'm trying to load an image to the cloud kit servers.

The image is saved ok in the core data graph > sqlite database.

The field name (photograph) doesn't show in the cloudkit dashboard.

The field is defined as binary data in the core data graph, and external storage is not enabled.

Any idea if I'm doing something wrong or where I should look further.

Thanks

**Comment by paulw11** [comment]
Can you show a snippet of code?  How do you put the image data in the `photograph` property?  Do you get any error messages in the console?

**Comment by daviddelmonte** [comment]
Hi Paul, thanks for helping. 

The field is described in the object chart as:

Attribute: photograph 
Type: Binary Data

This is the result of the image selection:
```

func imageChangeNotification(notification:Notification) -> Void {
   
        guard let imageDataDict = notification.userInfo!["imageData"] else { return }
        selectedImage  = UIImage(data: imageDataDict as! Data)!
        imageData = imageDataDict as! NSData
        mugShotView.image = selectedImage
    }

```
And this is where the record is saved:

```
 @IBAction func saveRecord(_ sender: AnyObject) {
         
        let person = people[0]  
        let timeStamp = Date.init()
        let context = (UIApplication.shared.delegate as! AppDelegate).persistentContainer.viewContext
   
        person.firstName = firstNameField.text
        person.lastName = lastNameField.text
       person.itemEditedDate = timeStamp as NSDate
        person.photograph = imageData
       
        do {
            try context.save()
        } catch let error as NSError  {
            print("Error While Saving Data: \(error.userInfo)")
        }
  
    }


```
The mugshot is saved in the database of the current computer, but not in CloudKit . In fact, I don't see a "photograph" field in the CloudKit dashboard.

Finally, I do see the following message in the console:

`[Generic] Creating an image format with an unknown type is an error`

Thanks again for any help.

**Comment by daviddelmonte** [comment]
Paul, I found it. I had to remove the entity from the CloudKit server, and let Seam regenerate the records. Hope this helps.

**Comment by paulw11** [comment]
I'm glad you fixed it.  You might also want to consider storing your photo using JPEG or PNG representation  - you can see an example in the sample in the Seam3 repo

**Comment by daviddelmonte** [comment]
Thanks Paul. I left out a bit of code where I resize the image.
