### ISSUE TITLE
changes not syncing

### ISSUE THREAD

**Issue by literalpie** [paulw11/Seam3#2]
This is an amazing framework, and it is successfully syncing data (pairs of strings) between devices. It works when I add new data, and when I remove data. However, when an existing piece of data is edited, the change is not applied to devices that have synced before. The update does show in the cloud dashboard, and If a new device is synced, the newest, correct version will be synced. 

I also can't figure out how to change the conflict resolution settings. I don't think this is related since it is supposed to default to accepting the cloud version.

**Comment by paulw11** [comment]
Have you enabled remote notifications and added a `didReceiveRemoteNotifications` method to your app delegate; see the Example app in the repo.  Also, the simulator won't receive the push notifications, so unfortunately a sync won't be triggered on a simulator if the data is changed elsewhere.  You should also call `triggerSync` when your app launches.

**Comment by literalpie** [comment]
That did it, thanks! I didn't think I needed to add that yet, but I guess I did
Thank you for the effort that you put into this! I've spent weeks trying to figure out how to approach CloudKit, and I was on the verge of giving up!

**Comment by paulw11** [comment]
You are welcome.  @nofelmahmood did a lot of the work, I just took his code and fixed up the bits that weren't working and upgraded it for Swift 3.
