### ISSUE TITLE
iOS11 - This does not obviate the need for Seam3

### ISSUE THREAD

**Issue by daviddelmonte** [paulw11/Seam3#23]
Hi Paul, do you agree that nothing in iOS11 obviates the need for Seam3. There do not seem to be enhancements to CloudKit that allows local storage. Please confirm or correct.

Thanks

David

**Comment by paulw11** [comment]
I haven't seen anything new from the WWDC videos.  There is a significant change to the Cloudkit dashboard that is already live, but no changes to CloudKit itself

**Comment by daviddelmonte** [comment]
Paul, in the new Dashboard, where can I find the SMStores for my apps? Sorry, long day..
