### ISSUE TITLE
Crash on unwrapping an Optional value

### ISSUE THREAD

**Issue by rvegas-zz** [paulw11/Seam3#24]
I'm experiencing a crash here
"fatal error: unexpectedly found nil while unwrapping an Optional value"
[Screenshot](https://pasteboard.co/GC8p4zH.png)

Case was like this:
1. Removed object on other device
2. Sync was performed successfully
3. Accessed removed object after sync on current device -> Crash

**Comment by paulw11** [comment]
Have you updated your Seam3 pod? This was fixed by #21 and your screen shot shows the previous code
