### ISSUE TITLE
Adding persistentStoreDescriptions breaks core data

### ISSUE THREAD

**Issue by Kautenja** [paulw11/Seam3#25]
When trying to get this framework integrated with an existing Core Data project I'm seeing some issues with the code in the README for setting up the persistentContainer for an iOS10 based application.

This is what the persistent container currently looks like; however, like this it seems to fail to load the model correctly as existing objects can no longer be fetched and attempting to insert into the persistentContainers viewContext is raising errors about missing NSEntity descriptions.

```swift
    lazy var persistentContainer: NSPersistentContainer = {
        SMStore.registerStoreClass()
        let container = NSPersistentContainer(name: "_Ring")
        let urls = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)
        
        guard let applicationDocumentsDirectory = urls.last else {
            fatalError("Unable to access documents directory")
        }
        let url = applicationDocumentsDirectory.appendingPathComponent("_Ring.sqlite")
        let storeDescription = NSPersistentStoreDescription(url: url)
        storeDescription.type = SMStore.type
        container.persistentStoreDescriptions = [storeDescription]
        container.loadPersistentStores(completionHandler: { (storeDescription, error) in
            if let error = error as NSError? {
                DispatchQueue.main.async(execute: {
                    PopupAlert.show(on: self.frontViewController!,
                                    title: "Failed to setup CloudKit",
                                    message: error.localizedDescription)
                })
            }
        })
        return container
    }()
```

I've narrowed it down to these 4 lines (as they're the only new lines really)

```swift
let url = applicationDocumentsDirectory.appendingPathComponent("_Ring.sqlite")
let storeDescription = NSPersistentStoreDescription(url: url)
storeDescription.type = SMStore.type
container.persistentStoreDescriptions = [storeDescription]
```

I've tried various filenames for the sqlite file to no avail. Removing those lines will bring back access to any data that had been created in the store on a previous install

removing this single line allows a clean install with no data to find NSEntity descriptions again and be able to create objects and fetch them again.

```swift
storeDescription.type = SMStore.type
```

not sure if the issue i'm having here is due to a bug or me not having set something up correctly, but to my knowledge I've followed the setup correctly and I'm positive my prior CoreData code works as it is entirely tested. any help/insight would be much appreciated.

**Comment by paulw11** [comment]
If you remove that line then you aren't using the Seam3 store, you are just using a plain sqlite store.  Have you logged into iCloud on your device or simulator?
