### ISSUE TITLE
Cloudkit: "client oplock error updating record"

### ISSUE THREAD

**Issue by daviddelmonte** [paulw11/Seam3#27]
Paul, I am getting this message from time to time. This [SO q/a](https://stackoverflow.com/questions/36012376/client-oplock-error-saving-records-in-cloudkit) seems to give a good understanding of how to workaround the problem.

Is this something you should add to Seam3? Or, something I should tinker with?

Thanks

**Comment by paulw11** [comment]
If this error occurs then you should get a message saying something like *Conflicted Record client oplock error updating record* - If you do, then this message is expected and Seam3 will then use your conflict resolution policy to determine if the server record or the local record wins (or call your conflict resolution closure if you have provided one).  If the message you are getting doesn't start with *Conflicted Record* then I would be interested to see what error you are getting, and if you can work out which bit of code is printing the message, that too.

**Comment by daviddelmonte** [comment]
Paul, here is a sample console log. I am seeing the "Conflicted Record" message. However, The sync keeps trying to repeat until I quit the sim.

```
Sync Started
Aborting sync; operation in progress
Conflicted Record <CKError 0x60400184ed00: "Server Record Changed" (14/2004); server message = "client oplock error updating record"; uuid = 66B821EE-C59B-43F2-85BA-D3EB5876D122; container ID = "iCloud.com.bohtech.Base">
Operation error <CKError 0x600001a42160: "Partial Failure" (2/1011); "Failed to modify some records"; uuid = 66B821EE-C59B-43F2-85BA-D3EB5876D122; container ID = "iCloud.com.bohtech.Base"; partial errors: {
	E1FE5182-93A6-4853-8848-9DA7DE022CDB:(SMStoreCloudStore_CustomZone:__defaultOwner__) = <CKError 0x60400184ec70: "Server Record Changed" (14/2004); server message = "client oplock error updating record"; uuid = 66B821EE-C59B-43F2-85BA-D3EB5876D122>
	... 1 "Batch Request Failed" CKError's omited ...
}>

```

**Comment by paulw11** [comment]
I have just updated to 1.2.4 that fixes an infinite loop on syncing when there are missing referenced records.  Can you try this and see if has helped with this issue too?

**Comment by daviddelmonte** [comment]
Will do. Thanks!

Written by a human, sent by a machine

On Aug 7, 2017, at 13:00, Paul Wilkinson <notifications@github.com> wrote:

I have just updated to 1.2.4 that fixes an infinite loop on syncing when there are missing referenced records. Can you try this and see if has helped with this issue too?

**Comment by daviddelmonte** [comment]
I'm getting some compile errors..  I'm using Xcode 9 b4.

The following 6 errors. Let me know if I should fix something..

NSManagedObject+CKRecord.swift:116:54: Type 'CKRecordZoneID' has no member 'smCloudStoreCustomZoneID'

NSManagedObject+CKRecord.swift:128:24: Type 'CKRecord' has no member 'recordWithEncodedFields'

NSManagedObject+CKRecord.swift:131:50: Type 'CKRecordZoneID' has no member 'smCloudStoreCustomZoneID'

SMStoreSyncOperation.swift:202:41: Value of type 'CKRecord' has no member 'encodedSystemFields'

SMStoreSyncOperation.swift:368:29: Value of type 'CKRecord' has no member 'createOrUpdateManagedObjectFromRecord'

SMServerStoreSetupOperation.swift:105:44: Type 'CKRecordZoneID' has no member 'smCloudStoreCustomZoneID'

**Comment by paulw11** [comment]
Hmm.  I have beta3 and I am not getting those errors.  Have you tried a 'clean' ?  I can try Beta 4 later, but I have a power cut right now :(

**Comment by daviddelmonte** [comment]
I'm getting conflicting results and not sure what to do. Your example compiles fine. Opening my project now results in one error:

`SMStore.swift:353:29: Static member 'type' cannot be used on instance of type 'SMStore'`

I'm now using b5. I haven't changed anything since my last message. I have my project stored in iCloud/Documents, and get the same result on two computers. 

I've rebooted, restarted Xcode etc.

Not sure what else to try.

David

**Comment by daviddelmonte** [comment]
FYI, reverting to 1.2.3 results in no errors.

**Comment by paulw11** [comment]
I am downloading b5 today and I will let you know what I find.  FYI there is a  swift4 branch in the repo now.

**Comment by daviddelmonte** [comment]
Hi Paul, I’m getting these two error messages in the Swift 4 testing — again strange — your sample app compiles, but my project does not. Are there some project settings I should change?

Errors:

SMStoreSyncOperation.swift:202:41: Value of type 'CKRecord' has no member ‘encodedSystemFields'

SMStoreSyncOperation.swift:368:29: Value of type 'CKRecord' has no member 'createOrUpdateManagedObjectFromRecord'

**Comment by paulw11** [comment]
I can only suggest the usual suspects; remove the derived data folders and clean the project.  Your project doesn't seem to be picking up the extension to `CKRecord`.  Those two functions are contained in `CKRecord+NSManagedObject.swift`
