### ISSUE TITLE
Existing database migration error

### ISSUE THREAD

**Issue by rvegas-zz** [paulw11/Seam3#28]
I've integrated Seam3 to existing project. It works perfect when I make clean app installation.

But I have an issue when I run the app over existing one with old data present. It cannot perform migration and crashes with error

`CoreData: error: -addPersistentStoreWithType:SQLite configuration:(null) URL:file:///var/mobile/Containers/Data/Application/1CD79E54-FF39-4B67-8884-83681200BFA1/Documents/Project.sqlite options:{
    NSInferMappingModelAutomaticallyOption = 1;
    NSMigratePersistentStoresAutomaticallyOption = 1;
} ... returned error Error Domain=NSCocoaErrorDomain Code=134110 "An error occurred during persistent store migration." UserInfo={destinationURL=file:///var/mobile/Containers/Data/Application/1CD79E54-FF39-4B67-8884-83681200BFA1/Documents/.Project.sqlite.migrationdestination_41b5a6b5c6e848c462a8480cd24caef3, reason=Cannot migrate store in-place: Validation error missing attribute values on mandatory destination attribute, NSUnderlyingError=0x16dca5c0 {Error Domain=NSCocoaErrorDomain Code=134110 "An error occurred during persistent store migration." UserInfo={attribute=sm_LocalStore_RecordID, entity=Street, reason=Validation error missing attribute values on mandatory destination attribute}}, sourceURL=file:///var/mobile/Containers/Data/Application/1CD79E54-FF39-4B67-8884-83681200BFA1/Documents/Project.sqlite} with userInfo dictionary {
    NSUnderlyingError = "Error Domain=NSCocoaErrorDomain Code=134110 \"An error occurred during persistent store migration.\" UserInfo={attribute=sm_LocalStore_RecordID, entity=Street, reason=Validation error missing attribute values on mandatory destination attribute}";
    destinationURL = "file:///var/mobile/Containers/Data/Application/1CD79E54-FF39-4B67-8884-83681200BFA1/Documents/.Project.sqlite.migrationdestination_41b5a6b5c6e848c462a8480cd24caef3";
    reason = "Cannot migrate store in-place: Validation error missing attribute values on mandatory destination attribute";
    sourceURL = "file:///var/mobile/Containers/Data/Application/1CD79E54-FF39-4B67-8884-83681200BFA1/Documents/Project.sqlite";
}`

Attribute "sm_LocalStore_RecordID" is mandatory. When I tried to change it to optional - error and crash is gone, but old data is lost.

Is there a way to integrate Seam3 to existing datamodel without losing old users data?

**Comment by paulw11** [comment]
Unfortunately this is a known problem with the way that the persistent store migration occurs. See #17 
You will need to write code to read each entity from your current store and recreate it in a new Seam3 store.
