### ISSUE TITLE
Endless loop when there's no related object

### ISSUE THREAD

**Issue by rvegas-zz** [paulw11/Seam3#29]
I have a case when in cloud there is a _CKRecord_ with a reference to non existing _CKRecord_. This leads to endless loop and crash when fetching it from cloud. 

Loop happens in _SMStoreSyncOperation_ in func _insertOrUpdateManagedObjects_.
_CKRecord_ with non existing reference is added to _deferredRecords_ array each time

```
if retry && !deferredRecords.isEmpty {
            try self.insertOrUpdateManagedObjects(fromCKRecords: deferredRecords, retry:true)
}
```

I don't have enough experience with CloudKit so any help on how to manage this case would be appreciated

Thanks

**Comment by paulw11** [comment]
It isn't supposed to retry indefinitely, but there may be a bug.  Can you provide any console output or details on the crash?

**Comment by rvegas-zz** [comment]
Here's the place where crash occurs + some console output (i've added log to count number of _insertOrUpdateManagedObjects_ calls): [https://pasteboard.co/GE7RM55.png](https://pasteboard.co/GE7RM55.png)

In cloud there's only one record. It has non-existing reference:

```
<CKRecord: 0x7fe72b4266c0; recordID=EB32EB3F-0793-4E22-BEF5-28F0165DBA3A:(SMStoreCloudStore_CustomZone:__defaultOwner__), recordChangeTag=2g, values={
    home = "<CKReference: 0x600000427580; recordID=<CKRecordID: 0x600000425e80; recordName=02CDE7AE-D4C8-45AF-BE79-7460E2C4D865, zoneID=SMStoreCloudStore_CustomZone:__defaultOwner__>>";
    name = "Name";
}, recordType=Door>
```
This record is the only one that is added to _deferredRecords_ array each time because of missing reference object and _insertOrUpdateManagedObjects_ is called again

**Comment by paulw11** [comment]
I have updated the code to retry the resolution of references no more than 5 times.  After that the sync will fail
