### ISSUE TITLE
"More Records Coming" repeatedly when user is not signed into iCloud

### ISSUE THREAD

**Issue by literalpie** [paulw11/Seam3#3]
When running the sample app (or my own app with Seam3), when the user is not signed into iCloud, there seems to be an infinite loop. "More Records Coming" is logged repeatedly, and CPU usage reaches 100%

**Comment by paulw11** [comment]
I am aware of this issue.  You can check for icloud availability using the following snippet:

    CKContainer.defaultContainer().accountStatusWithCompletionHandler { (status, error) in
            dispatch_async(dispatch_get_main_queue()) {
                if status != CKAccountStatus.Available {
                   // Display some alert prompting the user to log in to iCloud and enable iCloud Drive
                }
    }
