### ISSUE TITLE
Customer getting a new error message.

### ISSUE THREAD

**Issue by daviddelmonte** [paulw11/Seam3#31]
Paul, my app isn't using the latest version of Seam3. They are getting this console message:

`SMStoreCloudStore_CustomZone:__defaultOwner__ = <CKError 0x1740519d0: "Zone Not Found" (26/2036); server message = "Zone 'SMStoreCloudStore_CustomZone' does not exist">`

Before I go through the integration, testing and AppStore processes, I wonder if this error is familiar to you?

Thanks

**Comment by paulw11** [comment]
Hi David,

Have you migrated the CloudKit configuration to production if required?
Does the user have iCloud drive enabled on their device?

Seam3 will set up that zone if required; it uses a value in UserDefaults to
determine this.  If the iCloud user on the device has changed you need to
call `resetBackingStore` as is shown in the example (search the AppDelegate
for "New User") to ensure that user defaults is cleared and the zone is set
up for the new user.

Paul

**Comment by paulw11** [comment]
closed in error

**Comment by daviddelmonte** [comment]
Paul, I'm closing this. The customer (a friend) did not have the latest version of my app installed. Also, the Swift 4 version is now working for me.. So thanks!
