### ISSUE TITLE
Conflict resolution is borked

### ISSUE THREAD

**Issue by paulw11** [paulw11/Seam3#32]
Conflict resolution other than server wins doesn't work.

**Comment by paulw11** [comment]
@DJ-Glock Try version 1.3.2 and see how you go.  All three conflict resolution types now work and the iOS example App Delegate contains a (commented) example of a conflict resolution closure.

**Comment by DJ-Glock** [comment]
Thank you, Paul! I'll check this as soon as possible.

**Comment by DJ-Glock** [comment]
Hey Paul.
Have you updated pods or should I get project from github?
iGlockPro:CafeManager dj-glock$ pod list | grep Seam3
  Seam3 1.2.4
iGlockPro:CafeManager dj-glock$

**Comment by paulw11** [comment]
A `pod update` should get you the 1.3.1 update

**Comment by DJ-Glock** [comment]
Thanks mate! Not very experienced with pods. Apologies

**Comment by DJ-Glock** [comment]
Sorry for chasing you again. But have not faced issue like this last time when I imported Seam3.
Always getting this error after importing Seam3 framework. Is it something related to your changes? Or should I use Google?
![2017-09-01 16 14 08](https://user-images.githubusercontent.com/26511191/29971402-c322fb02-8f30-11e7-9539-a2aab176de80.jpg)

**Comment by DJ-Glock** [comment]
Sorry for chasing you again. But have not faced issue like this last time when I imported Seam3.
Always getting this error after importing Seam3 framework. Is it something related to your changes? Or should I use Google?
![2017-09-01 16 14 08](https://user-images.githubusercontent.com/26511191/29971671-c30dc95c-8f31-11e7-8030-43b875feba01.jpg)

**Comment by DJ-Glock** [comment]
File was located here:
/Users/dj-glock/Library/Developer/Xcode/DerivedData/CafeManagerWorkspace-bfgginmbcuzpmthgpcjneaqqbcpm/Build/Products/Debug-iphoneos/Seam3/
Other frameworks working with no issues. So I have copied framework to expected folder and build has been compiled.
Not sure if it's pods issue or something else. Just wanted to highlight it to you, just in case.
