### ISSUE TITLE
Batch delete possible?

### ISSUE THREAD

**Issue by daviddelmonte** [paulw11/Seam3#33]
Paul, in developing my app, I have a lot of extraneous widow objects.

EntityOne.object > EntityTwo.object
EntityOne.object > EntityThree.object

When I deleted EntityOne,  EntityTwo and EntityThree objects remained. This was a core-data graph relationship issue.

However, now that this is resolved, how should I best remove unwanted objects from the stores (CD and Cloudkit)?

Thanks

David

**Comment by daviddelmonte** [comment]
Forgot to add... As my app selects Server wins on conflict, I can go to the Cloudkit dashboard and remove unwanted objects -- but I can only do this for my own CK account. Not for test users, and real ones when I find bugs.

**Comment by paulw11** [comment]
All you need to do is clean up the Core Data store using any technique; either individual deletes or the batch delete operations available under Core Data; Seam3 will then sync these deletes back to the server

**Comment by daviddelmonte** [comment]
Paul, I'm using the following code to perform a batch delete:

self.deleteAllRecords(entity: self.someEntity)

And the function is:

  
   `self.deleteAllRecords(entity: self.someEntity)
  `
  
```
  
  func deleteAllRecords( entity : String)
    {
        let delegate = UIApplication.shared.delegate as! AppDelegate
        let context = delegate.persistentContainer.viewContext

        
        let fetch = NSFetchRequest<NSFetchRequestResult>(entityName: entity)
        let request = NSBatchDeleteRequest(fetchRequest: fetch)
        
        do {
            let result = try context.execute(request)
            print("result: ", result)
        }
        catch {
            print ("\(error)")
        }
        do {
            try context.save()
        } catch {
           print ("\(error)")
			}

```

I'm getting this error:` Error Domain=SMStoreErrorDomain Code=1 "(null)"`

What am I dong wrong?
