### ISSUE TITLE
CKErrorChangeTokenExpired error is not handled

### ISSUE THREAD

**Issue by rvegas-zz** [paulw11/Seam3#35]
Hi Paul,

Sometimes I got this error when fetching data on one device 
`<CKError 0x146dc1f0: "Change Token Expired" (21/2026); server message = "client knowledge differs from server knowledge"; uuid = C9218E09-7250-XXXX-XXXX-2FF4D5991456; container ID = "iCloud.com.xxxx.xxxxx">`

And as a result data cannot be synced. Here's what Apple suggests to do in such case

> If the server returns a CKErrorChangeTokenExpired error, the previousServerChangeToken value was too old and the client should toss its local cache and 
>         re-fetch the changes in this record zone starting with a nil previousServerChangeToken.

There's no handling of such errors in  _fetchRecordChangesFromServer()_.
I had to use temporary solution like below, but after this I should restart the app to make sync happen now with nil token

```
if let error = syncOperationError as! CKError? {
                if error.code == .changeTokenExpired {
                    SMServerTokenHandler.defaultHandler.delete()
                }
            }
```

**Comment by paulw11** [comment]
Thanks for opening this issue. I am currently away with very limited internet access, so I will take a look next week.

**Comment by paulw11** [comment]
A fix for this is now in the master branch.
