### ISSUE TITLE
How do I handle .SMSTOREERROR error 4?

### ISSUE THREAD

**Issue by daviddelmonte** [paulw11/Seam3#38]
I'm getting this error, after some manual messing with my data base. How should I recover? Thanks Paul!

David

**Comment by paulw11** [comment]
Do you have any other logs you can provide?

**Comment by daviddelmonte** [comment]
I cannot seem to reproduce this error, so I'm closing the issue.

**Comment by daviddelmonte** [comment]
No sooner had I closed the issue than it occurred again. However, I realized what is causing it. I had made some major changes to my data model. As a result, CloudKit could not reconcile the Record Types to my new model. Erasing the app from the devices did not work. I had to manually delete the affected record types. This fixed the issue.

**Comment by DJ-Glock** [comment]
I have faced similar issue on Test Environment after similar changes.

I believe the only thing we should worry about here is Application Release. I believe if major changes are made in data model, we need to release application in AppStore and promote CloudKit configuration to Production in the same time.

**Comment by daviddelmonte** [comment]
Thanks!
