### ISSUE TITLE
syncAutomatically should be false by default

### ISSUE THREAD

**Issue by tifroz** [paulw11/Seam3#44]
Let me explain: there are circumstances where the app doesn't have a reference to the `persistentStore`, therefore unable to do `store.syncAutomatically = false` before the store starts auto-synching.

One of these circumstances is when migrating an existing store to a `SMStore`: typically I will use an `NSMigrationManager` that will do all the build of the migration work to a `SMStore` given an `NSMappingModel`.
The `NSMigrationManager` will instantiate its own `SMStore` in the process ... and the records will automatically start sync'ing as part of the migration process because `syncAutomatically` is true by default.

It would be a lot cleaner if the app could prevent synchronization until the migration is complete, so it can do some validations (including validating the existence of an iCloud user) before turning on sync.

if it's important that `syncAutomatically` be on by default for most users, may I suggest using a static override option? So we still have the option to override the default without having access to the instance? Something like the code below
```
class SMStore  {
    static var syncAutomatically = true
    var syncAutomatically = true
    init() {
        self. syncAutomatically = SMStore.syncAutomatically
    }
}
```

Happy to submit a PR with your guidance if that's useful

**Comment by paulw11** [comment]
Good idea. I don't want to change the default since that may very well break existing apps, but the static property works well.
