### ISSUE TITLE
Static member 'type' cannot be used on instance...

### ISSUE THREAD

**Issue by bvelasquez** [paulw11/Seam3#49]
Getting Static member 'type' cannot be used on instance of type "SMStore" in SMStore.swift.

I'm using swift 4, but also tried using swift 3.2.  

override open func loadMetadata() throws {
        self.metadata=[
            NSStoreUUIDKey: ProcessInfo().globallyUniqueString,
            NSStoreTypeKey: type(of: self).type
        ]
        
        try self.createBackingStore()
    }

**Comment by paulw11** [comment]
Try version 1.4.3 which I have just released
