### ISSUE TITLE
edits do not sync

### ISSUE THREAD

**Issue by literalpie** [paulw11/Seam3#5]
I believe there actually is an issue with syncing edits. If a record is changed on one device, the change does not sync to the other device until the app is quit and restarted. Even if a change is made and then a new item is added on device A, device B will only get the new item added, not the changed item.
I did some digging to verify that this is an issue with Seam, not my own app, but I haven’t been able to nail down exactly where the problem is. When the change happens a sync is triggered. In CKRecord+NSManagedObject.swift, the createOrUpdateManagedObjectFromRecord function is run, and I am able to print out the old version of the entry, as well as the updated version by printing managedObject.value(forKey:) and self.value(forKey:) so the problem must occur after this point. One thing I found is that allCKReferencesAsManagedObjects seems to return an empty dictionary every time. At first glance, I thought this was the root of the problem, but the dictionary is empty even when an entry is new and the sync works.
For now I will work around this issue by deleting and replacing entries rather than updating them

**Comment by paulw11** [comment]
In your app,  where you handle the `SMStoreNotification.SyncDidFinish` notification, make sure you have something like `self.managedObjectContext?.refreshAllObjects()` to ensure that any in-memory objects are refreshed with the data from the backing store.

**Comment by literalpie** [comment]
yes, that was my issue. Thank you again!
