### ISSUE TITLE
More records coming repeatedly when signed into different iCloud account

### ISSUE THREAD

**Issue by literalpie** [paulw11/Seam3#6]
In the sample app or in my own app, If I log out of one iCloud account and then log into another iCloud account, the infinite loop of "more records coming" happens. This happens even with the verifyCloudKitConnection check. I'm guessing it's still trying to sync to the original account's cloud store and doesn't have permission

**Comment by paulw11** [comment]
I'll take a look at this.  Seam3 does store some sync details in `UserDefaults`, I will see if I can store the cloudkit identity somehow and detect changes.
