### ISSUE TITLE
Crash on Fetch Request

### ISSUE THREAD

**Issue by nbreeser** [paulw11/Seam3#7]
First, thank you so much for making this!

So I am experiencing a crash when 
`override open func newValue(forRelationship relationship: NSRelationshipDescription, forObjectWith objectID: NSManagedObjectID, with context: NSManagedObjectContext?) throws -> Any {`
returns NSNull
The crash is Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull count]: unrecognized selector sent to instance.

I am using the library with an objective C project. Not sure if that would have anything to do with weird optional stuff. Any help would be greatly appreciated!

**Comment by paulw11** [comment]
Is the crash occurring in your code? The `newValue` function will return NSNull if the relationship is optional and no related objects can be found, which is the correct behaviour as defined by Apple.  It looks like some code somewhere is assuming that the related object is an array and trying to get the count of objects in it, when it is actually an instance of `NSNull`

**Comment by nbreeser** [comment]
Hmmm, I think it is a core data method that is calling [NSNull count]; I'm still working on tracking down the culprit, but I'll let you know as soon as I do! Thank you for the quick reply!

**Comment by paulw11** [comment]
Ok.  I do recall seeing this during my development and testing.  Have you flagged your relationships as "optional" in your Core Data model?  I think that this is necessary.  Let me know if this helps and I will update documentation

**Comment by nbreeser** [comment]
Ah! Yes!! I accidentally had marked a non-optional relationship as optional in my model and somehow this hadn't caused problems earlier. Thank you!!!! Updating the model and reinstalling fixed the issue!

**Comment by nbreeser** [comment]
I just have to say thank you again. This is the first time my app has had syncing working consistently in years as it used to use core data sync which was an inconsistent mess. You are a life saver!

**Comment by daviddelmonte** [comment]
Echo that. I was just thinking the same thing! Thanks so much Paul.
