### ISSUE TITLE
Turn Off sync programmatically

### ISSUE THREAD

**Issue by ghost** [paulw11/Seam3#76]
Hello , I need to Turn Off Cloud Sync in my app by button action.
I try to use syncAutomatically by i can't help me.
How can i totally turn off sync in my code.

**Comment by DJ-Glock** [comment]
@dmtrwff 
Hi
Have you tried this code?
let appDelegate = UIApplication.shared.delegate as! AppDelegate
appDelegate.smStore?.syncAutomatically = false

I believe you can also create UserDefaults setting and disable it when app is launched with options:
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions:
...
self.smStore?.syncAutomatically = UserSettings.isAutosyncEnabled
...
