### ISSUE TITLE
Migration of an existing store fails

### ISSUE THREAD

**Issue by MaxHaertwig** [paulw11/Seam3#77]
Hello,
I incorporated Seam3 into my project and it works when using it in a newly installed app. However, when I try to migrate an existing core data store, SMStoreError.backingStoreCreationFailed is thrown and I get the following error message:
`attribute=sm_LocalStore_RecordID, Validation error missing attribute values on mandatory destination attribute`

Looking through the code, I found that recordIDAttribute.isOptional = false. When migrating the store, this attribute is nil and leads to the error above.

Is there any way to let Seam3 set the value when migrating, without having to do it manually?
Would it work to set isOptional to true before the migration and setting a default value (e.g. UUID().uuidString) for each managed object after the migration is finished?

**Comment by DJ-Glock** [comment]
@Vyax Hey Max.
Have you checked this issue and comments?
https://github.com/paulw11/Seam3/issues/59

And looking at your errors I suppose that you probably have missed some attributes in CloudKit schema. I suggest that you should double check CloudKit schema and ensure that there is no discrepancies between CoreData schema and CloudKit one.
