### ISSUE TITLE
Some iOS10 deprecations

### ISSUE THREAD

**Issue by daviddelmonte** [paulw11/Seam3#8]
I'm useless at Git, but there are some deprecations with iOS10. I can email changes as I fix them, or can you update.

**Comment by paulw11** [comment]
I am not aware of any iOS 10 deprecations in the current codebase. Can you provide some specific details?

**Comment by daviddelmonte** [comment]
Hi Paul, please see as follows:

SMStore.swift:250:30: Method 'initialize()' defines Objective-C class method 'initialize', which is not guaranteed to be invoked by Swift and will be disallowed in future versions

SMStoreSyncOperation.swift:254:105: 'CKOwnerDefaultName' was deprecated in iOS 10.0: Use CKCurrentUserDefaultName instead

SMServerStoreSetupOperation.swift:58:141: 'CKSubscriptionOptions' was deprecated in iOS 10.0: Use CKQuerySubscriptionOptions instead

'CKFetchRecordChangesOperation' was deprecated in iOS 10.0: Use CKFetchRecordZoneChangesOperation instead

SMServerStoreSetupOperation.swift:58:36: 'init(zoneID:subscriptionID:options:)' was deprecated in iOS 10.0: Use CKRecordZoneSubscription instead

**Comment by paulw11** [comment]
Oh yeah. *those* depreciations. Since Seam3 is targeted at ios9+ and I don't want to fill the source  with a bunch of `@available` and duplicated code, the deprecation will remain for the moment. It has no impact on functionality or operation.
