### ISSUE TITLE
Problem with size of tmp directory 

### ISSUE THREAD

**Issue by ghost** [paulw11/Seam3#85]
Hello , i use Asset to save UIImage in CoreData.
But i have problem with size of tmp directory.
May i save Asset without coping to tmp?

**Comment by ghost** [comment]
How can i sync asset without writing  data to tmp directory

**Comment by paulw11** [comment]
You have to save the asset somewhere, as `CKAsset` requires a file URL to upload it.

Is your problem with the size of a single asset or the cumulative size of assets in the tmp directory?

**Comment by ghost** [comment]
the cumulative size

**Comment by ghost** [comment]
Is CKAsset delete after uploading automatically?

**Comment by paulw11** [comment]
Seam3 does not remove the files from the temporary directory.  This is an enhancement that is probably needed.

Until I can do that you could use a technique such as [this](https://stackoverflow.com/questions/9196443/how-to-remove-tmp-directory-files-of-an-ios-app) to purge the temporary directory when you get the sync complete notification.

**Comment by ghost** [comment]
Many thanks for you support , I used common solution.
May the force be with you:)
