### ISSUE TITLE
i am a new user

### ISSUE THREAD

**Issue by avocet** [paulw11/Seam3#87]
I have a problem that I don't know why, please tell me.
_BSMachError: port 1ed17; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"

**Comment by paulw11** [comment]
This particular message isn't anything to do with Seam3.  Do you have a crash or exception message?

**Comment by avocet** [comment]
I can use seam to sync coreData in development version, but why not in production version( distribution ) ?   I can not access to the error information in distribution version, so can not post error information

**Comment by paulw11** [comment]
Did you copy your CloudKit environment to production in the CloudKit dashboard?

**Comment by avocet** [comment]
oh ! Thank you very much !
