### ISSUE TITLE
Swift 4.2?

### ISSUE THREAD

**Issue by daviddelmonte** [paulw11/Seam3#89]
Hi Paul, any plans for a Swift 4.2 branch?

**Comment by cenkalti** [comment]
FYI there is a PR about this: https://github.com/paulw11/Seam3/pull/88

**Comment by daviddelmonte** [comment]
Can I use the revised code before Paul merges it?

**Comment by cenkalti** [comment]
Not sure.

**Comment by daviddelmonte** [comment]
Many thanks to you Paul!
