### ISSUE TITLE
pod install in example directory fails with messages as shown

### ISSUE THREAD

**Issue by sundialsoft** [paulw11/Seam3#92]
I don't use POD normally so I'm not sure how to proceed. I'm an experienced dev converting to Swift 4 and writing a new app.

Specs satisfying the `Seam3 (from `../`)` dependency were found, but they required a higher minimum deployment target.

[!] Automatically assigning platform `ios` with version `10.0` on target `Seam3_Example` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] Automatically assigning platform `osx` with version `10.11` on target `Seam3_Example_OSX` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] Automatically assigning platform `tvos` with version `10.0` on target `Seam3_Example_TVOS` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by paulw11** [comment]
Fixed by 1.4.8
