### ISSUE TITLE
Performance issues: a lot of selects during saving context

### ISSUE THREAD

**Issue by DJ-Glock** [paulw11/Seam3#94]
Hello Paul.
My users started to face performance issues. I did some refactoring, but finally stuck with the following issue. It seems to be Seam3 issue.

I have enabled -com.apple.CoreData.SQLDebug 1 scheme and found that application performs a lot of fetches during saving context.
Let me show my data model:
<img width="928" alt="image" src="https://user-images.githubusercontent.com/26511191/47317679-e3a98480-d652-11e8-9fd6-0c430f9bc462.png">

There are many messages in TablesSessionTable (2k). And 386 records for table from example. And I'm trying to add another record into TableSessionTable for selected table. Here is my code:

```
import UIKit
import CoreData

class TableSessionTable: NSManagedObject {
    // MARK: variables
    static let tableSessionRequest: NSFetchRequest<TableSessionTable> = TableSessionTable.fetchRequest()
    
    // MARK: functions for managing sessions
    class func createTableSession (table: TablesTable) -> TableSessionTable {
        if #available(iOS 10.0, *) {
            let newTableSession = TableSessionTable(context: viewContext)
            newTableSession.openTime = Date() as NSDate
            newTableSession.closeTime = nil
            table.addToTableSession(newTableSession)
            try? viewContext.save()
            return newTableSession
        } else {
            let newTableSession = TableSessionTable(entity: NSEntityDescription.entity(forEntityName: "TableSessionTable", in: viewContext)!, insertInto: viewContext)
            newTableSession.openTime = Date() as NSDate
            newTableSession.closeTime = nil
            table.addToTableSession(newTableSession)
            try? viewContext.save()
            return newTableSession
        }
    }
    // a lot of code
}

extension TableSessionTable {
    @nonobjc public class func fetchRequest() -> NSFetchRequest<TableSessionTable> {
        return NSFetchRequest<TableSessionTable>(entityName: "TableSessionTable")
    }
    
    @NSManaged public var closeTime: NSDate?
    @NSManaged public var openTime: NSDate?
    @NSManaged public var totalAmount: Float
    @NSManaged public var totalTips: Float
    @NSManaged public var discount: Int16
    @NSManaged public var guest: NSSet?
    @NSManaged public var orderedItems: NSSet?
    @NSManaged public var table: TablesTable?
    
    // Supporting properties
    @objc var openTimeTruncatedToDay: String {
        return openTime!.getTimeStrWithDayPrecision()
    }
    @objc var openTimeTruncatedToMonth: String {
        return openTime!.getTimeStrWithMonthPrecision()
    }
    
    @objc var sessionDurationInSeconds: Double {
        let currentCloseTime = closeTime ?? NSDate()
        let period = currentCloseTime.timeIntervalSince1970 - openTime!.timeIntervalSince1970
        return period
    }
}


// MARK: Generated accessors for orderedItems
extension TableSessionTable {
    @objc(addOrderedItemsObject:)
    @NSManaged public func addToOrderedItems(_ value: OrdersTable)
    
    @objc(removeOrderedItemsObject:)
    @NSManaged public func removeFromOrderedItems(_ value: OrdersTable)
    
    @objc(addOrderedItems:)
    @NSManaged public func addToOrderedItems(_ values: NSSet)
    
    @objc(removeOrderedItems:)
    @NSManaged public func removeFromOrderedItems(_ values: NSSet)
}

// MARK: Generated accessors for guest
extension TableSessionTable {
    @objc(addGuestObject:)
    @NSManaged public func addToGuest(_ value: GuestsTable)
    
    @objc(removeGuestObject:)
    @NSManaged public func removeFromGuest(_ value: GuestsTable)
    
    @objc(addGuest:)
    @NSManaged public func addToGuest(_ values: NSSet)
    
    @objc(removeGuest:)
    @NSManaged public func removeFromGuest(_ values: NSSet)
}
```

And during saving context App performs a lot of fetches (388 actually, I believe one per each linked record).
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/26511191/47318298-6252f180-d654-11e8-900a-89c9890030cf.png">

Log attached.
[TableSessionCreation.log](https://github.com/paulw11/Seam3/files/2503313/TableSessionCreation.log)

Would you be so kind to take a look into the issue?

**Comment by paulw11** [comment]
The attached log represents a bit over half a second of wall-clock time, which doesn't seem excessive. You don't say whether this log represents the complete operation or whether multiple of these operations in which case the time would add up.

Do you have automatic sync enabled or are you triggering manual syncs?

A Time Profiler instrument report would probably be more helpful in identifying potential performance issues rather than an SQL log.

**Comment by DJ-Glock** [comment]
@paulw11 this log represents one operation (1 call of createTableSession function). And this is just an example. I can show you another log with another record creation when it causes delay about up to 1-2 seconds on a real device (iphone 4s) - about 1500 selects during saving context for 1 insert.
[AddingOrder.txt](https://github.com/paulw11/Seam3/files/2503395/AddingOrder.txt)


Auto sync is not enabled. Only manual syncs.

**Comment by paulw11** [comment]
My gut feel is that there isn't much that can be done because the selects are probably mapping the object IDs between the Seam store and the backing object context.  The context information from a time profiler report will help identify where the time is being spent and then we know where to look to try and improve performance.

**Comment by DJ-Glock** [comment]
Thanks, Paul.
