### ISSUE TITLE
CFBundleVersion is empty

### ISSUE THREAD

**Issue by lvandal** [paulw11/Seam3#99]
The `CFBundleVersion` parameter in `Info.plist` is empty, which the App Store complains about. I was able to workaround the issue by setting a value via plistbuddy but it seems like `$(CURRENT_PROJECT_VERSION)` is not defined.

**Comment by bcye** [comment]
Do you mean it is not defined in the xcconfig?

I can't replicate your issue.

**Comment by paulw11** [comment]
I can't reproduce this either. It sounds to me like a Pod integration problem.

**Comment by lvandal** [comment]
I'm not using CocoaPods, I'm using Carthage.

**Comment by jbuckner** [comment]
I'm also seeing this with Carthage.

**Comment by paulw11** [comment]
Yes, it is a Carthage issue.  I have seen other projects that include a ruby file to fix this when used with Carthage.  I am hesitant to simply replace the variable with a fixed value as it will create another point of maintenance.
